[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
graphics = { path = "../graphics" }
math = { path = "../math" }
nalgebra = "0.33.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
